version: '3.8'

services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

networks:
  default:
    name: cesium-recorder
